wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1654111526
    t:
      1:
      - 1
      - 5
      - 53
      - 54
      - 55
      3:
      - 13
      4: 3.8.12
      5: 0.12.17
      8:
      - 1
      - 3
      - 5
